### ISSUE TITLE
[Front] Have documentation section pages, using markdown (.md)

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#140]
Should have a style similar to the home page as much as possible

- change the title to have CronRobot in it
- change the default color mode to dark, if it's possible. I saw the html has that css: <html class="js-focus-visible dark" data-js-focus-visible=""> when it's dark
- and change if possible the favicon
mm for dark mode i think there is a config:
// theme.config.js
export default {
  customSearch: null, // customizable, you can use algolia for example
  darkMode: true,
 
}
- using the same font would be good also, if it looks good
- and also if there would be a way to have a link back to cronrobot.io

**Comment by kb24x7** [comment]
Done 👍
