### ISSUE TITLE
3D renders

### ISSUE THREAD

**Issue by kb24x7** [cronrobot/cronrobot#170]
3D renders for social media, etc.

**Comment by kb24x7** [comment]
![Big Logo](https://user-images.githubusercontent.com/61944452/129377889-6a4fa208-1e48-4dda-85dc-84ffa7f992f7.png)
![Clock-Only Golden (Pink BG)](https://user-images.githubusercontent.com/61944452/129377906-c6bc2db1-0924-449d-9ca5-2f8760099c30.png)
![Clock-Only Golden](https://user-images.githubusercontent.com/61944452/129377914-2095f26d-d737-4827-ae4f-38efed93231c.png)
![Clock-Only Silver](https://user-images.githubusercontent.com/61944452/129377919-3287b0ec-444a-464a-a73c-6a8b2a77fc02.png)
![Small Logo](https://user-images.githubusercontent.com/61944452/129377922-301626d1-0a80-4b76-948a-0a44c29f9b3b.png)

**Comment by kb24x7** [comment]
3D renders uploaded :)

**Comment by martinlevesque** [comment]
please create a pull request with the files

**Comment by kb24x7** [comment]
Created a PR: https://github.com/cronrobot/cronrobot/pull/171
