### ISSUE TITLE
In dashboard, user should be able to see which project he is in, and be able to switch to another one

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#205]
in any route, to switch to a different project: url/dashboard/path?selected_project_id=PROJECT ID

**Comment by martinlevesque** [comment]
@kb24x7 when you select a project is selected, it's not changing the path

**Comment by kb24x7** [comment]
> @kb24x7 when you select a project is selected, it's not changing the path

There was no project in accessible projects to test it out, it has been done right now, but I don't know what path to redirect to

**Comment by kb24x7** [comment]
It currently redirects to /dashboard?selected_project_id=id which is a valid path but it doesn't change the project, it is probably a rails issue.
