### ISSUE TITLE
Landing page should display flash errors, if any

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#219]
![image](https://user-images.githubusercontent.com/8007722/131336635-065eb33c-453e-4844-a0fe-83c06f641ed3.png)

see views/layouts/_flash_errors.html.erb

the scss, both in landing pages and dashboard should have error classes in order to display flash errors nicely, see https://stackoverflow.com/a/37469186

**Comment by kb24x7** [comment]
I would recommend using a JavaScript module to get a quick fix of this issue, what do you suggest?
