### ISSUE TITLE
Project new route, overrides @project

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#255]
change var name

**Comment by kb24x7** [comment]
Variable name needs to be changed in:
https://github.com/cronrobot/cronrobot/blob/e6b4b6f0f6fb4d5ecd47441fa89ed49de0c9bd77/www-cronrobot/app/controllers/dashboard/projects_controller.rb#L5

**Comment by martinlevesque** [comment]
will be in @updated_project
