### ISSUE TITLE
If logged in, the home still show to login

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#257]
![image](https://user-images.githubusercontent.com/8007722/133176997-46ddb772-e5ad-4c90-ae1d-d4172e04d2bb.png)

**Comment by kb24x7** [comment]
This looks like a rails issue again
![Screen Shot 2021-09-14 at 11 25 10 AM](https://user-images.githubusercontent.com/61944452/133202651-d22fbc29-e36c-4e5b-b745-63d338b94cba.png)

**Comment by kb24x7** [comment]
Everything looks good on my side

**Comment by martinlevesque** [comment]
Just re-tested. I am logged in in the dashboard, then I go back to the home. and here's a screenshot

![image](https://user-images.githubusercontent.com/8007722/133436955-3f620d63-cc0d-4885-be4b-bf3d9c315ce6.png)
