### ISSUE TITLE
Dashboard layout does not show enough useful content

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#259]
Pages with lists should contain 10 or 15 items at least. Currently half the page is taken by the menu, and only 3-4 schedulers are shown. It should be improved to be more useful.

![image](https://user-images.githubusercontent.com/8007722/133177964-b101c1af-d6f4-48c2-916c-8df91b2dd74b.png)

**Comment by kb24x7** [comment]
I can reduce the margin between the heading and the navbar but I think everything else is taking up space as low as possible 
¯\_(ツ)_/¯

**Comment by martinlevesque** [comment]
well if you could please have a look.

if you look for example at the github site:

there are like 10 items you can view. and the menus on the top do not take so much space. In our site, we can only see like 4 items, and the menu takes almost half a page, it's too big IMO

![image](https://user-images.githubusercontent.com/8007722/133437818-8c827290-f6c3-43e8-b5b0-94df9c048426.png)

**Comment by kb24x7** [comment]
Fixed 👍

**Comment by martinlevesque** [comment]
@kb24x7 looks much better.

if we could see 8 or 10 items, instead of 6 it would be better IMO. see below a screenshot

![image](https://user-images.githubusercontent.com/8007722/133780817-ae4dc0c5-7c08-4755-bcaa-7cf584b47968.png)

**Comment by kb24x7** [comment]
Managed to get 7 on the screen 👍

**Comment by kb24x7** [comment]
You can close this issue after reviewing
