### ISSUE TITLE
Fields placeholds should be light grey instead of black

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#264]
you cannot know if it's filled or not, until you click on the field

![image](https://user-images.githubusercontent.com/8007722/133780929-12161349-d5e2-4f46-899a-eec3dac75c30.png)

**Comment by kb24x7** [comment]
Fixed 👍

**Comment by martinlevesque** [comment]
it should be more light. currently difficult to know if it's a normal text, or a placeholder

**Comment by kb24x7** [comment]
Fixed 👍
