### ISSUE TITLE
Add labels in field areas

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#265]
We should know what the fields are. labels should be added

![image](https://user-images.githubusercontent.com/8007722/133781097-b564efee-a05a-4772-89e4-6f216411676f.png)

**Comment by kb24x7** [comment]
Hi, there are already placeholders for input fields, adding labels is not very...mainstream, I can do it but it wouldn't look as good as a placeholder

**Comment by martinlevesque** [comment]
@kb24x7 if you could just add an example and comment it

**Comment by kb24x7** [comment]
Added a template and commented it 👍 

![Screen Shot 2021-09-18 at 10 31 21 PM](https://user-images.githubusercontent.com/61944452/133896615-93d4b738-7b54-4f5f-9d7d-03e6e92d0590.png)
