### ISSUE TITLE
Links transparent in scheduler list, in name

### ISSUE THREAD

**Issue by martinlevesque** [cronrobot/cronrobot#277]
![image](https://user-images.githubusercontent.com/8007722/133908407-3a2ec80c-2ed9-4a15-8323-6d19ec830f96.png)

**Comment by kb24x7** [comment]
Fixed 👍

**Comment by martinlevesque** [comment]
it should have an effect when you hover - should be like that everywhere, all links

**Comment by kb24x7** [comment]
Done 👍

**Comment by martinlevesque** [comment]
There is no effect on hover
And also a link should have a different color - please make them the same color everywhere in the website so that it's clear to the user that a link is a link

**Comment by kb24x7** [comment]
Try looking for the :hover tag for that element in inspect element

**Comment by kb24x7** [comment]
Made the link look more like a link

**Comment by kb24x7** [comment]
https://github.com/cronrobot/cronrobot/commit/b16ff8dc2b69abe8c9c5c153115a46f225f5bef9

**Comment by martinlevesque** [comment]
It still very difficult to know if it's a link, see screenshot

![image](https://user-images.githubusercontent.com/8007722/134170748-222c0165-a550-41db-9927-2a93a5e78cd0.png)
